name: picturesourcesomerset
version: 1.0.0+1
publish_to: none
description: Picture Source Somerset - Learn Martial Arts Online | Self Defence | Fitness.
environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.1.0
  intl_phone_number_field: ^0.2.0
  otp_text_field: ^1.1.3
  calendar_date_picker2: ^1.1.5
  get_cli: ^1.9.1
  get: ^4.6.6
  image_picker: ^1.0.0
  syncfusion_flutter_charts: ^28.1.35
  flutter_rating_bar: ^4.0.1
  getwidget: ^5.0.0
  story_view: ^0.16.5
  url_launcher: ^6.1.12
  #rich_readmore: ^1.1.1
  image_cropper: ^9.0.0
  permission_handler: ^11.3.1
  flutter_switch: ^0.3.2
  file_picker: ^8.1.4
  open_file: ^3.3.2
  quickalert: ^1.1.0
  expandable: ^5.0.1
  video_player: ^2.9.1
  chewie: ^1.8.2
  flutter_webrtc: ^0.12.3
  flutter_secure_storage: ^9.2.2
  dio: ^5.6.0
  flutter_html: ^3.0.0-beta.2
  google_sign_in: ^6.2.1
  shared_preferences: ^2.3.3
  flutter_plugin_android_lifecycle: ^2.0.24
  flutter_staggered_grid_view: ^0.7.0
  carousel_slider: ^5.0.0
  flutter_stripe: ^11.3.0


dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  collection: ^1.18.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/avatar.png
    - assets/default-logo.png
    - assets/live.png
    - assets/logo-long.png
    - assets/order_success.png
    - assets/pss1.png
    - assets/pss2.png
    - assets/pss3.png
    - assets/pss4.png
    - assets/pss5.png
    - assets/pss6.png
    - assets/pss7.png
    - assets/pss8.png
    - assets/pss9.png
    - assets/slider1.png
    - assets/slider2.png
    - assets/slider3.png
    - assets/splash-logo.png
    - assets/splash-logo22.png
  fonts:
    - family: Urbanist-Black
      fonts:
        - asset: asset/Urbanist-Black.ttf
    - family: Urbanist-Bold
      fonts:
        - asset: asset/Urbanist-Bold.ttf
    - family: Urbanist-Medium
      fonts:
        - asset: asset/Urbanist-Medium.ttf
    - family: Urbanist-Regular
      fonts:
        - asset: asset/Urbanist-Regular.ttf
    - family: Urbanist-SemiBold
      fonts:
        - asset: asset/Urbanist-SemiBold.ttf
