/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'picturesourcesomerset';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String AVATAR = 'assets/avatar.png';
  static const String LIVE = 'assets/live.png';
  static const String LOGO_LONG = 'assets/logo-long.png';
  static const String PSS1 = 'assets/pss1.png';
  static const String PSS2 = 'assets/pss2.png';
  static const String PSS3 = 'assets/pss3.png';
  static const String PSS4 = 'assets/pss4.png';
  static const String PSS5 = 'assets/pss5.png';
  static const String PSS6 = 'assets/pss6.png';
  static const String PSS7 = 'assets/pss7.png';
  static const String PSS8 = 'assets/pss8.png';
  static const String PSS9 = 'assets/pss9.png';
  static const String SLIDER1 = 'assets/slider1.png';
  static const String SLIDER2 = 'assets/slider2.png';
  static const String SLIDER3 = 'assets/slider3.png';
  static const String SPLASH_LOGO = 'assets/splash-logo.png';
  static const String SPLASH_LOGO22 = 'assets/splash-logo22.png';
}
