/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class FontRes {
  FontRes._();

  static const String PLUGIN_NAME = 'picturesourcesomerset';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String URBANIST_BLACK = 'Urbanist-Black';
  static const String URBANIST_BOLD = 'Urbanist-Bold';
  static const String URBANIST_MEDIUM = 'Urbanist-Medium';
  static const String URBANIST_REGULAR = 'Urbanist-Regular';
  static const String URBANIST_SEMIBOLD = 'Urbanist-SemiBold';
}
